management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true
info.app.name=Hotel Room Allocation System
info.app.description=API for hotel room occupancy optimization based on willingness to pay.
info.app.version=0.0.1-SNAPSHOT
# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
